### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by p-j**
Hi 👋🏻 

Thanks for your packages, I've been testing the prisma/trpc/zod stack recently and your generators are awesome to get started.

This PR upgrades dependencies, namely `@trpc/server` to v10
It updates the import of `MiddlewareFunction` following the move to [reusable Middlewares](https://trpc.io/docs/middlewares)

This fixes some errors I had around the permissions types when using [omar-dulaimi/prisma-trpc-shield-generator ](https://github.com/omar-dulaimi/prisma-trpc-shield-generator) with a `@trpc/server^10` stack

### CODE REVIEW

**Comment by omar-dulaimi** [comment]
Hey @p-j 

Thank you for your PR, it's highly appreciated.
Though for the time being, it won't be merged. I plan on starting working on the upgrade to v10 when it hits stable.
But if I had some free time, I might integrate your PR in a release candidate on a different branch. But I cant promise anything for now,

Thank you again :)

**Comment by jwyce** [comment]
@omar-dulaimi now that v10 is out do you have any idea what the timeline might look like for v10 support?

**Comment by omar-dulaimi** [comment]
Hey @p-j 
I have just upgraded this project to tRPC v10. You can try `0.2.1`.
Thanks for the PR, though it won' be needed anymore.
 
:)

**Comment by omar-dulaimi** [comment]
As for `prisma-trpc-generator`, it will be updated very soon as the PR have reached it's final steps.

**Pull request closed without merging**
