### PR TITLE
Ensure fallbackRule is used when rule not found.

### PR DESCRIPTION
**Pull request by royletron**
Hey. I have been trying this out on a project and really need the fallbackRule (always deny!). I spotted that it was being ignored.

### CODE REVIEW

**Comment by omar-dulaimi** [comment]
Hey @royletron 

Thanks for the PR. I assume you tested it and it's working for you?

**Comment by royletron** [comment]
@omar-dulaimi yeah, tested locally and it works as I expect.

**Comment by omar-dulaimi** [comment]
LGTM!

**Comment by omar-dulaimi** [comment]
Released in https://github.com/omar-dulaimi/trpc-shield/releases/tag/0.1.2

**Pull request merged**
